--
--
--
SET @SABS = 'MSH,SNOMEDCT_US,NCBI,FMA,GO,HGNC';
SET @SUPPRESS = 'N';
SET @LATS = 'ENG';

DROP TABLE IF EXISTS BIO_MRCONSO;
CREATE TABLE BIO_MRCONSO AS
    SELECT * FROM MRCONSO
        WHERE find_in_set(SUPPRESS, @SUPPRESS)
          AND find_in_set(SAB, @SABS)
          AND find_in_set(LAT, @LATS);

DROP TABLE IF EXISTS BIO_MRREL;
CREATE TABLE BIO_MRREL AS
    SELECT * FROM MRREL
    WHERE find_in_set(SUPPRESS, @SUPPRESS)
          AND find_in_set(SAB, @SABS)
          AND find_in_set(LAT, @LATS)
    ORDER BY REL, RELA;

DELETE FROM `BIO_MRREL` WHERE CUI1=CUI2;

DROP TABLE IF EXISTS BIO_MRSTY;
CREATE TABLE BIO_MRSTY AS
    SELECT * FROM MRSTY
    WHERE CUI IN (SELECT DISTINCT CUI FROM BIO_MRCONSO);

-- INSERT INTO BIO_MRDEF
    -- SELECT * FROM MRDEF
    -- WHERE CUI IN (SELECT DISTINCT CUI FROM BIO_MRCONSO);

DROP TABLE IF EXISTS BIO_MRDEF;
CREATE TABLE BIO_MRDEF AS
SELECT * FROM MRDEF
    WHERE ATUI IN (
      SELECT
        (SELECT d.ATUI FROM MRDEF d
         WHERE d.CUI = c.CUI ORDER BY LENGTH(d.DEF)
         LIMIT 1)  AS ATUI
    FROM BIO_MRCONSO c)

