CREATE TABLE indexdata AS
   SELECT LUI , STR, GROUP_CONCAT(DISTINCT CUI) AS CUIS,
             GROUP_CONCAT(DISTINCT CONCAT( SAB, ':', CODE )) AS CODES
   FROM MRCONSO
   WHERE LAT = 'ENG'
     AND SAB IN ('MSH', 'SNOMEDCT_US', 'NCBI', 'GO', 'HGNC', 'FMA')
     AND SUPPRESS IN ('N')
   GROUP BY LUI
   ORDER BY LUI;

ALTER TABLE  `indexdata` ADD  `TUIS` VARCHAR( 250 ) NOT NULL;
ALTER TABLE  `indexdata` ADD  `MODIFIED` TINYINT NOT NULL DEFAULT 0;

UPDATE indexdata i
SET TUIS = (SELECT GROUP_CONCAT(DISTINCT TUI) FROM MRSTY s
    WHERE FIND_IN_SET(s.CUI, i.CUIS) > 0);

ALTER TABLE indexdata ADD PRIMARY KEY(LUI);

CREATE TABLE temp_str AS SELECT STR FROM indexdata WHERE RIGHT(STR, 1) <> ')';
ALTER TABLE temp_str ADD INDEX(STR(255));

DELETE FROM indexdata WHERE STR LIKE '%(foundation metadata concept)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 29)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(context-dependent category)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 28)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(morphologic abnormality)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 25)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(administrative concept)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 24)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(navigational concept)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 22)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(contextual qualifier)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 22)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(geographic location)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(religion/philosophy)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(biological function)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(separate procedure)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 20)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(namespace concept)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 19)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(observable entity)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 19)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(assessment scale)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 18)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(record artifact)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(allelic variant)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(qualifier value)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(living organism)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(physical object)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(cell structure)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(surface region)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(physical force)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(regime/therapy)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(body structure)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(tumor staging)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(clinical exam)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(staging scale)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(combined site)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(manifestation)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(invertebrate)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 14)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(ethnic group)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 14)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(environment)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 13)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(Drosophila)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(medication)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(occupation)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(attribute)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(procedure)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(substance)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(diagnosis)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(treatment)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(situation)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(eukaryote)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(diagnosis)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(superior)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(inferior)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(obsolete)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(bacteria)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(lab test)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(disorder)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(specimen)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(organism)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(Medicine)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(etiology)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(function)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(property)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(disease)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(finding)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(product)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(symptom)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(degrees)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(history)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(lateral)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(person)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(fungus)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(medial)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(device)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(action)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(event)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(yeast)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(human)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(PLANT)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)) IN (SELECT STR FROM temp_str);
DELETE FROM indexdata WHERE STR LIKE '%(cell)'
    AND TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 6)) IN (SELECT STR FROM temp_str);

UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 29)), MODIFIED=1
    WHERE STR LIKE '%(foundation metadata concept)'     ;
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 28)), MODIFIED=1
    WHERE STR LIKE '%(context-dependent category)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 25)), MODIFIED=1
    WHERE STR LIKE '%(morphologic abnormality)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 24)), MODIFIED=1
    WHERE STR LIKE '%(administrative concept)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 22)), MODIFIED=1
    WHERE STR LIKE '%(navigational concept)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 22)), MODIFIED=1
    WHERE STR LIKE '%(contextual qualifier)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)), MODIFIED=1
    WHERE STR LIKE '%(geographic location)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)), MODIFIED=1
    WHERE STR LIKE '%(religion/philosophy)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 21)), MODIFIED=1
    WHERE STR LIKE '%(biological function)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 20)), MODIFIED=1
    WHERE STR LIKE '%(separate procedure)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 19)), MODIFIED=1
    WHERE STR LIKE '%(namespace concept)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 19)), MODIFIED=1
    WHERE STR LIKE '%(observable entity)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 18)), MODIFIED=1
    WHERE STR LIKE '%(assessment scale)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)), MODIFIED=1
    WHERE STR LIKE '%(record artifact)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)), MODIFIED=1
    WHERE STR LIKE '%(allelic variant)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)), MODIFIED=1
    WHERE STR LIKE '%(qualifier value)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)), MODIFIED=1
    WHERE STR LIKE '%(living organism)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 17)), MODIFIED=1
    WHERE STR LIKE '%(physical object)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)), MODIFIED=1
    WHERE STR LIKE '%(cell structure)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)), MODIFIED=1
    WHERE STR LIKE '%(surface region)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)), MODIFIED=1
    WHERE STR LIKE '%(physical force)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)), MODIFIED=1
    WHERE STR LIKE '%(regime/therapy)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 16)), MODIFIED=1
    WHERE STR LIKE '%(body structure)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)), MODIFIED=1
    WHERE STR LIKE '%(tumor staging)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)), MODIFIED=1
    WHERE STR LIKE '%(clinical exam)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)), MODIFIED=1
    WHERE STR LIKE '%(staging scale)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)), MODIFIED=1
    WHERE STR LIKE '%(combined site)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 15)), MODIFIED=1
    WHERE STR LIKE '%(manifestation)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 14)), MODIFIED=1
    WHERE STR LIKE '%(invertebrate)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 14)), MODIFIED=1
    WHERE STR LIKE '%(ethnic group)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 13)), MODIFIED=1
    WHERE STR LIKE '%(environment)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)), MODIFIED=1
    WHERE STR LIKE '%(Drosophila)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)), MODIFIED=1
    WHERE STR LIKE '%(medication)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 12)), MODIFIED=1
    WHERE STR LIKE '%(occupation)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(attribute)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(procedure)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(substance)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(diagnosis)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(treatment)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(situation)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(eukaryote)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 11)), MODIFIED=1
    WHERE STR LIKE '%(diagnosis)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(superior)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(inferior)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(obsolete)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(bacteria)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(lab test)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(disorder)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(specimen)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(organism)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(Medicine)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(etiology)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(function)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 10)), MODIFIED=1
    WHERE STR LIKE '%(property)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(disease)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(finding)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(product)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(symptom)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(degrees)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(history)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 9)), MODIFIED=1
    WHERE STR LIKE '%(lateral)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)), MODIFIED=1
    WHERE STR LIKE '%(person)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)), MODIFIED=1
    WHERE STR LIKE '%(fungus)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)), MODIFIED=1
    WHERE STR LIKE '%(medial)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)), MODIFIED=1
    WHERE STR LIKE '%(device)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 8)), MODIFIED=1
    WHERE STR LIKE '%(action)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)), MODIFIED=1
    WHERE STR LIKE '%(event)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)), MODIFIED=1
    WHERE STR LIKE '%(yeast)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)), MODIFIED=1
    WHERE STR LIKE '%(human)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 7)), MODIFIED=1
    WHERE STR LIKE '%(PLANT)';
UPDATE indexdata SET STR= TRIM(SUBSTRING(STR, 1, LENGTH(STR) - 6)), MODIFIED=1
    WHERE STR LIKE '%(cell)';

